/**
 * The `.blindqa/` folder: one fixed layout for every project. Nothing in it is ever committed or pushed
 * (see guard.mjs): its own .gitignore is "*", so git ignores the whole folder, that file included.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

/** [path inside .blindqa/, what it holds]. Folders end with "/". */
export const LAYOUT = [
  ['README.md', 'What this folder is (regenerated by blindqa)'],
  ['.gitignore', '"*" — git ignores everything in here, this file included'],
  ['profile.json', 'How to reach the app: apps, roles, start commands, safety rules'],
  ['credentials.json', 'Who signs in as each role (owner-only file permissions)'],
  ['.env', 'Optional environment values for runs, e.g. MAILPIT_URL'],
  ['journeys/', 'Journey scripts (.mjs) written for this app'],
  ['index/', 'Code index: the commit it was built from, a hash and the extracted facts of every file, import graph, test coverage'],
  ['runs/', 'One folder per run: summary.md, findings.jsonl, map.json, routes.json, shots/, trace.log'],
  ['jobs/', 'Background jobs, one JSON each'],
  ['reports/', 'Findings registers and reports written for people'],
  ['sessions/', 'Saved sign-ins per role'],
  ['browser-profile/', 'Profile of the local blindqa browser window'],
]

const README = `# .blindqa — local QA data (never committed, never pushed)

Created by blindqa. Git ignores this whole folder: its own \`.gitignore\` is \`*\`, the repo's
\`.git/info/exclude\` lists it, and a \`pre-push\` hook refuses any push that contains it.
Check with \`blindqa guard\`.

${LAYOUT.map(([p, what]) => `- \`${p}\` — ${what}`).join('\n')}

Deleting this folder removes everything blindqa knows about the app; the app itself is untouched.
`

/** Create the folders, the self-ignoring .gitignore and the README. Safe to call on every start. */
export function ensureLayout(dir) {
  for (const [p] of LAYOUT) if (p.endsWith('/')) mkdirSync(join(dir, p), { recursive: true })
  const ignore = join(dir, '.gitignore')
  if (!existsSync(ignore) || readFileSync(ignore, 'utf8').trim() !== '*') writeFileSync(ignore, '*\n')
  const readme = join(dir, 'README.md')
  if (!existsSync(readme) || readFileSync(readme, 'utf8') !== README) writeFileSync(readme, README)
  return dir
}
